name: gh-release

on:
  push:
    branches:
      - main
    paths:
      - "**/RELEASE"
  workflow_dispatch:

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pipe-cd/actions-gh-release@v2.6.0
        with:
          release_file: "**/RELEASE"
          token: ${{ secrets.GITHUB_TOKEN }}
  build-pdf:
    needs: [gh-release]
    uses: BIwashi/resume/.guthub/workflows/build-pdf.yml@main