name: lint text

on: 
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: lint text
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - run: pnpm install
      - name: lint text
        run: pnpm run lint
