name: Update docs README

on:
  push:
    paths:
      - "README.md"

jobs:
  copy-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy README.md to /docs
        run: cp README.md docs/README.md

      - name: Set up Git user
        run: |
          git config --local user.email "saxo-folatre1129@outlook.jp"
          git config --local user.name "BIwashi"

      - name: Commit and push
        run: |
          git add docs/README.md
          git commit -m "Update docs README.md" || exit 0
          git push
      - name: Trigger lint text workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: lint-text
