name: Update docs README
on:
  push:
    paths:
      - 'README.md'
jobs:
  copy-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy README.md to /docs
        run: cp README.md docs/README.md
      - name: Set up Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Commit and push
        run: |
          git checkout -b update-docs-readme
          git add docs/README.md
          git commit -m "Update docs README.md" || exit 0
          git push origin update-docs-readme
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-docs-readme
          title: Update docs README.md
          body: This PR updates the README.md in /docs.